name: Deploy to IPFS with Pinata

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install Dependencies
      run: npm install @pinata/web3.sdk

    - name: Deploy to IPFS
      env:
        PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
        PINATA_SECRET_API_KEY: ${{ secrets.PINATA_SECRET_API_KEY }}
      run: |
        echo "Deploying files to IPFS using the new SDK"
        node <<EOF
        const { PinataClient } = require('@pinata/web3.sdk');
        const fs = require('fs');

        const pinata = new PinataClient({
          pinataApiKey: process.env.PINATA_API_KEY,
          pinataSecretApiKey: process.env.PINATA_SECRET_API_KEY,
        });

        async function deployToIPFS() {
          try {
            console.log("Authenticating...");
            await pinata.testAuthentication();

            console.log("Pinning directory...");
            const result = await pinata.pinFromFS('./');
            console.log("Successfully pinned:", result);
          } catch (error) {
            console.error("Error during deployment:", error);
            process.exit(1);
          }
        }

        deployToIPFS();
        EOF



