name: Deploy to IPFS with Pinata

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to IPFS with Pinata
      uses: popovoleksandr/ipfs-pinata-deploy-action@v1.0.0
      with:
        pinataApiKey: ${{ secrets.PINATA_API_KEY }}
        pinataSecretApiKey: ${{ secrets.PINATA_SECRET_API_KEY }}
        pathToUpload: ./  # The directory to upload (root in this case)
