name: Deploy to IPFS with Pinata

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x  # Use a compatible Node.js version

    - name: Install Dependencies
      run: npm install @pinata/sdk

    - name: Deploy to IPFS
      env:
        PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
        PINATA_SECRET_API_KEY: ${{ secrets.PINATA_SECRET_API_KEY }}
      run: |
        echo "Deploying files to IPFS"
        node <<EOF
        const pinataSDK = require('@pinata/sdk');
        const fs = require('fs');

        const pinata = pinataSDK(process.env.PINATA_API_KEY, process.env.PINATA_SECRET_API_KEY);

        async function deploy() {
          try {
            console.log("Authenticating...");
            await pinata.testAuthentication();
            console.log("Authentication successful.");

            console.log("Pinning directory...");
            const result = await pinata.pinFromFS('./'); // Pins the root directory
            console.log("Successfully pinned:", result);
          } catch (error) {
            console.error("Error during deployment:", error);
            process.exit(1);
          }
        }

        deploy();
        EOF


