name: Deploy to IPFS with Pinata

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install Dependencies
      run: npm install @pinata/sdk

    - name: Deploy to IPFS
      env:
        PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
        PINATA_SECRET_API_KEY: ${{ secrets.PINATA_SECRET_API_KEY }}
      run: |
        echo "Deploying files to IPFS using Pinata SDK"
        node <<EOF
        const pinataSDK = require('@pinata/sdk');
        const pinata = pinataSDK(process.env.PINATA_API_KEY, process.env.PINATA_SECRET_API_KEY);

        pinata.testAuthentication()
          .then(() => {
            return pinata.pinFromFS('./');
          })
          .then((result) => {
            console.log('Successfully pinned:', result);
          })
          .catch((err) => {
            console.error('Error during pinning:', err);
            process.exit(1);
          });
        EOF
